import type {
  Ad, AIAnalysis, AdVariation, Campaign, DashboardStats, HistoryEntry,
  PlatformMixItem, PerformanceLoopEntry, AIRecommendation,
  PlatformAccount, ImportedCampaign, PlatformSyncEvent, PlatformRecommendation,
  PricingPlan,
} from './types';

// ─── Local placeholder images (public/ads/) — no external dependency ─────────
const IMG = {
  fitness:  '/ads/fitness.svg',
  coffee:   '/ads/coffee.svg',
  shoes:    '/ads/shoes.svg',
  skincare: '/ads/skincare.svg',
  tech:     '/ads/tech.svg',
  travel:   '/ads/travel.svg',
  food:     '/ads/food.svg',
  fashion:  '/ads/fashion.svg',
};

// ─── Campaigns ────────────────────────────────────────────────────────────────
export const mockCampaigns: Campaign[] = [
  { id: 'c1', name: 'Q1 Brand Awareness', status: 'active', budget: 15000, spend: 11240, startDate: '2026-01-01', adsCount: 8, platform: 'facebook', objective: 'Awareness' },
  { id: 'c2', name: 'Spring Conversion Push', status: 'active', budget: 25000, spend: 18900, startDate: '2026-03-01', adsCount: 12, platform: 'google', objective: 'Conversions' },
  { id: 'c3', name: 'TikTok Gen-Z Launch', status: 'paused', budget: 8000, spend: 7200, startDate: '2026-02-01', endDate: '2026-03-31', adsCount: 5, platform: 'tiktok', objective: 'Traffic' },
  { id: 'c4', name: 'LinkedIn B2B Leads', status: 'active', budget: 12000, spend: 4500, startDate: '2026-04-01', adsCount: 6, platform: 'linkedin', objective: 'Leads' },
];

// ─── Ads ──────────────────────────────────────────────────────────────────────
export const mockAds: Ad[] = [
  {
    id: 'ad1',
    name: 'FitLife — Pain Point Hero',
    platform: 'facebook',
    status: 'active',
    imageUrl: IMG.fitness,
    headline: 'Stop Wasting Hours at the Gym',
    description: 'Our AI coach builds your perfect 20-min workout. 94% of users see results in 30 days or they get their money back.',
    cta: 'Start Free Trial',
    campaign: 'Q1 Brand Awareness',
    campaignId: 'c1',
    createdAt: '2026-01-15',
    updatedAt: '2026-04-10',
    aiScore: 91,
    tags: ['fitness', 'pain-point', 'guarantee', 'social-proof'],
    budget: 3000,
    format: 'image',
    objective: 'conversions',
    metrics: {
      ctr: 4.82, cpc: 0.94, cpm: 12.40, cpa: 18.50, roas: 6.8,
      conversions: 1247, reach: 312000, impressions: 892000, clicks: 43000,
      spend: 23000, revenue: 156400, frequency: 2.9,
    },
  },
  {
    id: 'ad2',
    name: 'BrewHaven — Morning Ritual',
    platform: 'instagram',
    status: 'active',
    imageUrl: IMG.coffee,
    headline: 'Your Morning Deserves Better Coffee',
    description: 'Single-origin beans roasted to order. Delivered fresh to your door within 48 hours of roasting.',
    cta: 'Shop Now',
    campaign: 'Spring Conversion Push',
    campaignId: 'c2',
    createdAt: '2026-03-02',
    updatedAt: '2026-04-12',
    aiScore: 78,
    tags: ['lifestyle', 'premium', 'freshness', 'ecommerce'],
    budget: 2000,
    format: 'image',
    objective: 'sales',
    metrics: {
      ctr: 3.21, cpc: 1.48, cpm: 18.90, cpa: 34.20, roas: 3.9,
      conversions: 489, reach: 156000, impressions: 423000, clicks: 13600,
      spend: 16800, revenue: 65520, frequency: 2.7,
    },
  },
  {
    id: 'ad3',
    name: 'NovaSole — Speed vs Style',
    platform: 'tiktok',
    status: 'active',
    imageUrl: IMG.shoes,
    headline: 'Fast Enough for PRs. Clean Enough for Brunch.',
    description: 'The running shoe that doubles as a streetwear flex. 4.9 ⭐ from 12K+ runners.',
    cta: 'Shop the Drop',
    campaign: 'TikTok Gen-Z Launch',
    campaignId: 'c3',
    createdAt: '2026-02-10',
    updatedAt: '2026-03-28',
    aiScore: 87,
    tags: ['gen-z', 'lifestyle', 'social-proof', 'dual-use'],
    budget: 2500,
    format: 'video',
    objective: 'traffic',
    metrics: {
      ctr: 5.67, cpc: 0.72, cpm: 9.80, cpa: 28.40, roas: 5.1,
      conversions: 634, reach: 890000, impressions: 2100000, clicks: 119000,
      spend: 42900, revenue: 218790, frequency: 2.4,
      videoViews: 1560000, videoViewRate: 74,
    },
  },
  {
    id: 'ad4',
    name: 'GlowLab — Before/After Authority',
    platform: 'instagram',
    status: 'active',
    imageUrl: IMG.skincare,
    headline: 'Dermatologist-Developed. Actually Works.',
    description: '98% see visible improvement in 21 days. No harsh chemicals. No empty promises. Just science.',
    cta: 'Try Risk-Free',
    campaign: 'Spring Conversion Push',
    campaignId: 'c2',
    createdAt: '2026-03-15',
    updatedAt: '2026-04-14',
    aiScore: 95,
    tags: ['authority', 'skincare', 'guarantee', 'science-backed'],
    budget: 3500,
    format: 'carousel',
    objective: 'conversions',
    metrics: {
      ctr: 6.14, cpc: 0.88, cpm: 11.20, cpa: 22.10, roas: 7.4,
      conversions: 1892, reach: 445000, impressions: 1240000, clicks: 76100,
      spend: 41600, revenue: 307840, frequency: 2.8,
    },
  },
  {
    id: 'ad5',
    name: 'Nexus AI — ROI Calculator Hook',
    platform: 'linkedin',
    status: 'active',
    imageUrl: IMG.tech,
    headline: 'How Much Revenue Is Your Ops Team Leaving on the Table?',
    description: 'Calculate your savings in 60 seconds. 500+ enterprise teams cut costs by avg. 34% with Nexus AI.',
    cta: 'Calculate My ROI',
    campaign: 'LinkedIn B2B Leads',
    campaignId: 'c4',
    createdAt: '2026-04-02',
    updatedAt: '2026-04-15',
    aiScore: 82,
    tags: ['b2b', 'saas', 'roi', 'question-hook', 'enterprise'],
    budget: 4000,
    format: 'image',
    objective: 'leads',
    metrics: {
      ctr: 2.18, cpc: 4.20, cpm: 38.50, cpa: 112.00, roas: 8.9,
      conversions: 201, reach: 48000, impressions: 132000, clicks: 2880,
      spend: 22500, revenue: 200250, frequency: 2.75,
    },
  },
  {
    id: 'ad6',
    name: 'Wanderlux — Scarcity Escape',
    platform: 'facebook',
    status: 'paused',
    imageUrl: IMG.travel,
    headline: '72-Hour Flash Sale: Bali from $649',
    description: 'Only 23 packages left at this price. All-inclusive 7-night escapes with 5-star resorts. Sale ends Sunday.',
    cta: 'Book Before It\'s Gone',
    campaign: 'Q1 Brand Awareness',
    campaignId: 'c1',
    createdAt: '2026-02-20',
    updatedAt: '2026-03-10',
    aiScore: 73,
    tags: ['scarcity', 'travel', 'flash-sale', 'urgency'],
    budget: 1500,
    format: 'image',
    objective: 'sales',
    metrics: {
      ctr: 7.82, cpc: 0.61, cpm: 8.90, cpa: 145.00, roas: 4.2,
      conversions: 78, reach: 98000, impressions: 287000, clicks: 22400,
      spend: 11300, revenue: 47460, frequency: 2.93,
    },
  },
  {
    id: 'ad7',
    name: 'TasteLab — UGC Recipe Hook',
    platform: 'tiktok',
    status: 'draft',
    imageUrl: IMG.food,
    headline: 'I Made Michelin-Star Pasta in 15 Minutes. Here\'s How.',
    description: 'Our chefs box delivers restaurant-grade ingredients and foolproof recipes. First box 50% off.',
    cta: 'Get My First Box',
    campaign: 'Spring Conversion Push',
    campaignId: 'c2',
    createdAt: '2026-04-16',
    updatedAt: '2026-04-16',
    aiScore: undefined,
    tags: ['ugc', 'food', 'social-proof', 'discount'],
    budget: 2000,
    format: 'video',
    objective: 'conversions',
    metrics: {
      ctr: 0, cpc: 0, cpm: 0, cpa: 0, roas: 0,
      conversions: 0, reach: 0, impressions: 0, clicks: 0,
      spend: 0, revenue: 0, frequency: 0,
    },
  },
  {
    id: 'ad8',
    name: 'LuxeThread — Lifestyle Aspiration',
    platform: 'instagram',
    status: 'completed',
    imageUrl: IMG.fashion,
    headline: 'Dress Like You Mean It',
    description: 'Sustainable luxury fashion curated by stylists who\'ve dressed for Vogue, Net-a-Porter, and your closet.',
    cta: 'Explore Collection',
    campaign: 'Q1 Brand Awareness',
    campaignId: 'c1',
    createdAt: '2025-11-01',
    updatedAt: '2026-01-31',
    aiScore: 68,
    tags: ['luxury', 'fashion', 'lifestyle', 'sustainability'],
    budget: 5000,
    format: 'carousel',
    objective: 'awareness',
    metrics: {
      ctr: 2.94, cpc: 2.10, cpm: 24.50, cpa: 67.80, roas: 2.8,
      conversions: 312, reach: 234000, impressions: 678000, clicks: 19900,
      spend: 21200, revenue: 59360, frequency: 2.9,
    },
  },
];

// ─── AI Analyses ──────────────────────────────────────────────────────────────
export const mockAnalyses: AIAnalysis[] = [
  {
    id: 'ana1',
    adId: 'ad1',
    adName: 'FitLife — Pain Point Hero',
    createdAt: '2026-04-10T14:32:00Z',
    model: 'claude-3-5-sonnet',
    overallScore: 91,
    copyScore: 94,
    visualScore: 87,
    audienceScore: 92,
    hookStrength: 96,
    estimatedCTR: 4.9,
    estimatedROAS: 7.1,
    strengths: [
      'Hook directly addresses a universal pain point ("wasting hours") — triggers immediate emotional resonance',
      'Social proof number (94%) is specific and believable — vague % claims often feel fabricated',
      'Money-back guarantee removes the primary purchase objection before it forms',
      'Call-to-action "Start Free Trial" lowers commitment friction to near-zero',
    ],
    weaknesses: [
      'Image shows generic gym stock photo — a real user transformation would outperform 3x',
      'Description lacks a specific time-to-result claim beyond "30 days"',
      'No mention of the AI element in the headline — missed differentiation opportunity',
    ],
    patterns: [
      { name: 'Pain-Point Hook', description: 'Opens with user frustration before the solution', impact: 'positive', confidence: 97, frequency: 12 },
      { name: 'Specific Social Proof', description: 'Uses precise % instead of round numbers', impact: 'positive', confidence: 89, frequency: 8 },
      { name: 'Risk Reversal', description: 'Money-back guarantee in body copy', impact: 'positive', confidence: 94, frequency: 6 },
      { name: 'Generic Visual', description: 'Stock image without human transformation', impact: 'negative', confidence: 82, frequency: 15 },
    ],
    recommendations: [
      'Replace stock image with before/after UGC transformation photo — test with real user consent',
      'Add "in just 20 minutes/day" to headline for specificity: "Stop Wasting Hours at the Gym — 20 min is enough"',
      'Test a curiosity variant: "The 20-Minute Workout Secret 50,000 Athletes Use"',
      'Add a subtle countdown or limited-offer element to test urgency lift',
    ],
    sentiment: 'positive',
    predictedPerformance: 'high',
  },
  {
    id: 'ana2',
    adId: 'ad4',
    adName: 'GlowLab — Before/After Authority',
    createdAt: '2026-04-14T09:15:00Z',
    model: 'claude-opus-4',
    overallScore: 95,
    copyScore: 97,
    visualScore: 93,
    audienceScore: 91,
    hookStrength: 94,
    estimatedCTR: 6.2,
    estimatedROAS: 7.8,
    strengths: [
      '"Dermatologist-Developed" establishes authority in first two words — crucial for skeptical skincare buyers',
      '"Actually Works" disarms cynicism by acknowledging the category\'s credibility problem',
      '21-day specificity creates a mental commitment window — users can visualize the journey',
      '"No harsh chemicals. No empty promises." two-punch objection handler with rhythm',
    ],
    weaknesses: [
      'CTA "Try Risk-Free" is slightly generic — "Start My 21-Day Trial" would reinforce the time-frame hook',
      'Missing influencer or dermatologist name for face-to-claim association',
    ],
    patterns: [
      { name: 'Authority Credentialing', description: 'Professional backing stated upfront', impact: 'positive', confidence: 98, frequency: 7 },
      { name: 'Cynicism Disarmer', description: 'Acknowledges category skepticism head-on', impact: 'positive', confidence: 91, frequency: 4 },
      { name: 'Objection Pre-emption', description: 'Handles objections before they form', impact: 'positive', confidence: 95, frequency: 9 },
      { name: 'Timeline Specificity', description: 'Concrete days instead of vague "fast results"', impact: 'positive', confidence: 88, frequency: 6 },
    ],
    recommendations: [
      'Test CTA: "Start My 21-Day Transformation" — reinforces body copy timeline',
      'Add a dermatologist name to headline: "Dr. Chen\'s Lab-Proven Formula"',
      'Create a carousel variant: each slide addresses one objection visually',
    ],
    sentiment: 'positive',
    predictedPerformance: 'high',
  },
  {
    id: 'ana3',
    adId: 'ad3',
    adName: 'NovaSole — Speed vs Style',
    createdAt: '2026-03-28T16:45:00Z',
    model: 'gpt-4o',
    overallScore: 87,
    copyScore: 89,
    visualScore: 85,
    audienceScore: 90,
    hookStrength: 88,
    estimatedCTR: 5.5,
    estimatedROAS: 5.3,
    strengths: [
      'Dual-identity positioning ("PRs & brunch") targets a real audience tension — athletes who value aesthetics',
      'TikTok-native language ("the drop") signals platform awareness and Gen-Z fluency',
      'Review count (12K+) lends credible weight without being overwhelming',
    ],
    weaknesses: [
      'Semicolon in headline creates a reading pause — TikTok copy should flow unbroken',
      'Price anchor missing — Gen-Z converts better when they know cost upfront',
      'Video hook (first 1.5s) needs a physical action or pattern interrupt',
    ],
    patterns: [
      { name: 'Dual-Identity Hook', description: 'Product works for two opposing use-cases', impact: 'positive', confidence: 92, frequency: 3 },
      { name: 'Platform-Native Language', description: 'Copy uses platform-specific slang correctly', impact: 'positive', confidence: 86, frequency: 8 },
      { name: 'Missing Price Anchor', description: 'No price mention when audience expects transparency', impact: 'negative', confidence: 79, frequency: 11 },
    ],
    recommendations: [
      'Rewrite headline removing semicolon: "Fast Enough for PRs. Clean Enough for Brunch." (periods work better)',
      'Add price to description: "Starts at $129 — free 30-day returns"',
      'Open video with a 0.5s split-screen: race track / coffee shop transition',
    ],
    sentiment: 'positive',
    predictedPerformance: 'high',
  },
];

// ─── Variations ───────────────────────────────────────────────────────────────
export const mockVariations: AdVariation[] = [
  {
    id: 'var1',
    originalAdId: 'ad1',
    originalAdName: 'FitLife — Pain Point Hero',
    createdAt: '2026-04-11T10:00:00Z',
    headline: 'The 20-Minute Workout Secret 50,000 Athletes Swear By',
    description: 'Stop spending 2 hours at the gym and getting worse results. Our AI coach designs your perfect short session — personalized to your body, goals, and schedule.',
    cta: 'Build My Workout',
    imagePrompt: 'Split-screen: left shows frustrated person in crowded gym, right shows confident athlete finishing 20-min home workout, bright natural light, authentic UGC style',
    imageUrl: IMG.fitness,
    predictedCTR: 5.4,
    predictedCPC: 0.82,
    predictedROAS: 7.8,
    confidence: 87,
    angle: 'Curiosidad',
    recommendedPlatform: 'facebook',
    status: 'testing',
    model: 'claude-3-5-sonnet',
    rationale: 'Curiosity hook replaces pain-point — tests whether aspiration outperforms frustration framing for this audience.',
    changeType: 'both',
  },
  {
    id: 'var2',
    originalAdId: 'ad1',
    originalAdName: 'FitLife — Pain Point Hero',
    createdAt: '2026-04-11T10:02:00Z',
    headline: 'Stop Wasting Hours at the Gym — 20 Minutes Is All You Need',
    description: '94% of our users see real results in 30 days. If you don\'t, you pay nothing. Your AI coach is waiting.',
    cta: 'Start Free Trial',
    imagePrompt: 'Real person doing home workout, sweating authentically, natural morning light, no stock-photo feel, phone showing workout app on floor beside them',
    imageUrl: IMG.fitness,
    predictedCTR: 5.1,
    predictedCPC: 0.88,
    predictedROAS: 7.2,
    confidence: 91,
    angle: 'Directa',
    recommendedPlatform: 'facebook',
    status: 'approved',
    model: 'claude-3-5-sonnet',
    rationale: 'Adds time specificity to headline while keeping proven pain-point structure. Low-risk, high-confidence test.',
    changeType: 'copy',
  },
  {
    id: 'var3',
    originalAdId: 'ad4',
    originalAdName: 'GlowLab — Before/After Authority',
    createdAt: '2026-04-15T08:30:00Z',
    headline: 'Start My 21-Day Skin Transformation',
    description: 'Dermatologist-formulated. 98% see visible results. No harsh chemicals — just the science your skin has been waiting for.',
    cta: 'Claim My Free Sample',
    imagePrompt: 'Clean flatlay of skincare products with subtle before/after skin texture cards, clinical but warm aesthetic, pastel laboratory backdrop',
    imageUrl: IMG.skincare,
    predictedCTR: 6.8,
    predictedCPC: 0.71,
    predictedROAS: 8.1,
    confidence: 88,
    angle: 'Oferta',
    recommendedPlatform: 'instagram',
    status: 'pending',
    model: 'claude-opus-4',
    rationale: 'Moves CTA copy into headline as action-first hook. Free sample offer lowers barrier vs. risk-free purchase.',
    changeType: 'both',
  },
  {
    id: 'var4',
    originalAdId: 'ad2',
    originalAdName: 'BrewHaven — Morning Ritual',
    createdAt: '2026-04-12T14:20:00Z',
    headline: 'Your Coffee Was Roasted 48 Hours Ago. Most Aren\'t.',
    description: 'Single-origin beans. Roasted to order. At your door before you can finish your current bag.',
    cta: 'Get Fresh Coffee',
    imagePrompt: 'Close-up of coffee beans being poured, warm amber light, steam rising, artisan roastery feel, golden hour tones',
    imageUrl: IMG.coffee,
    predictedCTR: 4.1,
    predictedCPC: 1.28,
    predictedROAS: 5.2,
    confidence: 76,
    angle: 'Directa',
    recommendedPlatform: 'instagram',
    status: 'approved',
    model: 'gpt-4o',
    rationale: 'Contrast hook — creates implicit comparison that makes competitor staleness visceral without naming them.',
    changeType: 'copy',
  },
];

// ─── Dashboard Stats ──────────────────────────────────────────────────────────
export const mockDashboardStats: DashboardStats = {
  totalSpend: 178300,
  totalRevenue: 1055620,
  avgROAS: 5.92,
  avgCTR: 4.39,
  totalConversions: 4853,
  totalImpressions: 5752000,
  activeAds: 5,
  analysesRun: 23,
  variationsGenerated: 41,
  topPerformingAd: 'GlowLab — Before/After Authority',
  spendTrend: [22000, 25400, 19800, 27600, 24100, 30200, 29200],
  revenueTrend: [128000, 148000, 112000, 165000, 143000, 182000, 177620],
  ctaTrend: [3.8, 4.1, 3.9, 4.6, 4.2, 4.8, 4.9],
  // Extended KPIs
  campaignsRunning: 3,
  variationsTested: 12,
  winningAds: 4,
  estimatedAvgROAS: 6.8,
  realAvgROAS: 5.92,
};

// ─── Platform Mix ─────────────────────────────────────────────────────────────
export const mockPlatformMix: PlatformMixItem[] = [
  { platform: 'facebook',  spend: 42300, pct: 34, roas: 5.4, ctr: 4.2 },
  { platform: 'instagram', spend: 34800, pct: 27, roas: 6.1, ctr: 4.8 },
  { platform: 'tiktok',    spend: 26200, pct: 21, roas: 5.1, ctr: 5.7 },
  { platform: 'google',    spend: 15000, pct: 12, roas: 7.2, ctr: 2.9 },
  { platform: 'linkedin',  spend:  7500, pct:  6, roas: 8.9, ctr: 2.2 },
];

// ─── Performance Loop ─────────────────────────────────────────────────────────
export const mockPerformanceLoop: PerformanceLoopEntry[] = [
  {
    id: 'loop1',
    adId: 'ad1',
    adName: 'FitLife — Pain Point Hero',
    stage: 'test',
    projectedCTR: 5.4,
    realCTR: 5.1,
    projectedROAS: 7.8,
    realROAS: 6.8,
    recommendation: 'Scale budget 20% — performance is consistent across 6 days',
    recommendationType: 'scale',
    confidence: 'high',
    daysActive: 6,
  },
  {
    id: 'loop2',
    adId: 'ad4',
    adName: 'GlowLab — Before/After Authority',
    stage: 'improve',
    projectedCTR: 6.8,
    realCTR: 7.2,
    projectedROAS: 8.1,
    realROAS: 7.4,
    recommendation: 'Duplicate campaign — top performer across all active ads',
    recommendationType: 'duplicate',
    confidence: 'high',
    daysActive: 3,
  },
  {
    id: 'loop3',
    adId: 'ad3',
    adName: 'NovaSole — Speed vs Style',
    stage: 'measure',
    projectedCTR: 5.5,
    realCTR: 5.67,
    projectedROAS: 5.3,
    realROAS: 5.1,
    recommendation: 'Continue testing — projections align with real data so far',
    recommendationType: 'monitor',
    confidence: 'medium',
    daysActive: 9,
  },
  {
    id: 'loop4',
    adId: 'ad2',
    adName: 'BrewHaven — Morning Ritual',
    stage: 'learn',
    projectedCTR: 4.1,
    realCTR: 3.21,
    projectedROAS: 5.2,
    realROAS: 3.9,
    recommendation: 'Test a different CTA — current copy underperforms projection',
    recommendationType: 'test_cta',
    confidence: 'medium',
    daysActive: 14,
  },
];

// ─── AI Recommendations ───────────────────────────────────────────────────────
export const mockRecommendations: AIRecommendation[] = [
  {
    id: 'rec1',
    adId: 'ad1',
    adName: 'FitLife — Pain Point Hero',
    type: 'scale',
    title: 'Scale Budget — FitLife',
    description: 'Estimated and real ROAS are aligned at 6.8x. Suggested increase of 20% in daily budget based on stable 6-day performance. Projected estimate: higher reach without efficiency loss.',
    impact: 'high',
    confidence: 88,
    metric: 'Real ROAS',
    metricValue: '6.8x',
  },
  {
    id: 'rec2',
    adId: 'ad6',
    adName: 'Wanderlux — Scarcity Escape',
    type: 'pause',
    title: 'Review — Wanderlux',
    description: 'CPA of $145 exceeds campaign target by 2.3x. High CTR (7.82%) suggests strong audience interest, but the conversion funnel needs review before resuming spend.',
    impact: 'high',
    confidence: 91,
    metric: 'CPA vs Target',
    metricValue: '$145 vs $63',
  },
  {
    id: 'rec3',
    adId: 'ad2',
    adName: 'BrewHaven — Morning Ritual',
    type: 'test_cta',
    title: 'Test New CTA — BrewHaven',
    description: '"Shop Now" underperforms similar ads using action-oriented CTAs by 1.3%. Suggested alternatives based on data available: "Try My First Bag" or "Get Fresh Coffee Now".',
    impact: 'medium',
    confidence: 74,
    metric: 'CTR gap',
    metricValue: '3.21% vs 4.5% avg',
  },
  {
    id: 'rec4',
    adId: 'ad4',
    adName: 'GlowLab — Before/After Authority',
    type: 'duplicate',
    title: 'Duplicate Campaign — GlowLab',
    description: 'Top performer across all active ads with real ROAS 7.4x. Replicating to Instagram Stories format may capture additional high-intent traffic based on audience overlap data.',
    impact: 'medium',
    confidence: 81,
    metric: 'Real ROAS',
    metricValue: '7.4x — top active',
  },
];

// ─── History ─────────────────────────────────────────────────────────────────
export const mockHistory: HistoryEntry[] = [
  { id: 'h1', type: 'analysis', title: 'AI Analysis Completed', description: 'GlowLab Before/After Authority analysed — Score: 95/100', createdAt: '2026-04-14T09:15:00Z', relatedAdId: 'ad4', relatedAdName: 'GlowLab — Before/After Authority', model: 'claude-opus-4', score: 95 },
  { id: 'h2', type: 'variation', title: 'Variations Generated', description: '2 new variations created for FitLife — Pain Point Hero', createdAt: '2026-04-11T10:02:00Z', relatedAdId: 'ad1', relatedAdName: 'FitLife — Pain Point Hero', model: 'claude-3-5-sonnet' },
  { id: 'h3', type: 'analysis', title: 'AI Analysis Completed', description: 'FitLife Pain Point Hero analysed — Score: 91/100', createdAt: '2026-04-10T14:32:00Z', relatedAdId: 'ad1', relatedAdName: 'FitLife — Pain Point Hero', model: 'claude-3-5-sonnet', score: 91 },
  { id: 'h4', type: 'ad_added', title: 'New Ad Added', description: 'TasteLab UGC Recipe Hook added as draft', createdAt: '2026-04-16T08:00:00Z', relatedAdId: 'ad7', relatedAdName: 'TasteLab — UGC Recipe Hook' },
  { id: 'h5', type: 'variation', title: 'Variation Approved', description: 'BrewHaven contrast hook variant approved for testing', createdAt: '2026-04-12T14:20:00Z', relatedAdId: 'ad2', relatedAdName: 'BrewHaven — Morning Ritual', model: 'gpt-4o' },
  { id: 'h6', type: 'analysis', title: 'AI Analysis Completed', description: 'NovaSole Speed vs Style analysed — Score: 87/100', createdAt: '2026-03-28T16:45:00Z', relatedAdId: 'ad3', relatedAdName: 'NovaSole — Speed vs Style', model: 'gpt-4o', score: 87 },
  { id: 'h7', type: 'metric_update', title: 'Metrics Synced', description: 'All active ads refreshed from platform APIs', createdAt: '2026-04-17T06:00:00Z' },
  { id: 'h8', type: 'variation', title: 'Variation Generated', description: 'GlowLab 21-Day Transformation variant ready for review', createdAt: '2026-04-15T08:30:00Z', relatedAdId: 'ad4', relatedAdName: 'GlowLab — Before/After Authority', model: 'claude-opus-4' },
];

// ─── Platform Accounts ────────────────────────────────────────────────────────
export const mockPlatformAccounts: PlatformAccount[] = [
  {
    id: 'pa-meta',
    platform: 'meta',
    name: 'AdGenius Demo · Meta Business',
    accountId: 'act_827461930',
    connected: true,
    status: 'connected',
    connectedSince: '2026-02-14T10:00:00Z',
    lastSync: '2026-05-06T06:00:00Z',
    tokenExpiresAt: '2026-07-04T10:00:00Z',
    daysUntilExpiry: 59,
    adsImported: 24,
    campaignsImported: 4,
    currency: 'USD',
    timezone: 'America/New_York',
  },
  {
    id: 'pa-google',
    platform: 'google',
    name: 'Google Ads Account',
    accountId: '—',
    connected: false,
    status: 'disconnected',
    adsImported: 0,
    campaignsImported: 0,
    currency: 'USD',
    timezone: '—',
  },
];

// ─── Imported Campaigns ───────────────────────────────────────────────────────
export const mockImportedCampaigns: ImportedCampaign[] = [
  {
    id: 'ic1',
    platform: 'meta',
    name: 'Q1 Brand Awareness',
    objective: 'Brand Awareness',
    status: 'active',
    dailyBudget: 500,
    totalBudget: 15000,
    spend: 11240,
    impressions: 308000,
    clicks: 12928,
    conversions: 208,
    ctr: 4.2,
    cpc: 0.87,
    roas: 5.4,
    estimatedROAS: 5.8,
    adsCount: 8,
    startDate: '2026-01-01',
    lastUpdated: '2026-05-06T06:00:00Z',
  },
  {
    id: 'ic2',
    platform: 'meta',
    name: 'Spring Conversion Push',
    objective: 'Conversions',
    status: 'active',
    dailyBudget: 830,
    totalBudget: 25000,
    spend: 18900,
    impressions: 532000,
    clicks: 25548,
    conversions: 380,
    ctr: 4.8,
    cpc: 0.74,
    roas: 6.1,
    estimatedROAS: 6.5,
    adsCount: 12,
    startDate: '2026-03-01',
    lastUpdated: '2026-05-06T06:00:00Z',
  },
  {
    id: 'ic3',
    platform: 'meta',
    name: 'GlowLab Remarketing',
    objective: 'Conversions',
    status: 'active',
    dailyBudget: 350,
    totalBudget: 10500,
    spend: 6400,
    impressions: 145000,
    clicks: 10298,
    conversions: 290,
    ctr: 7.1,
    cpc: 0.62,
    roas: 8.2,
    estimatedROAS: 7.9,
    adsCount: 4,
    startDate: '2026-03-15',
    lastUpdated: '2026-05-06T06:00:00Z',
  },
  {
    id: 'ic4',
    platform: 'meta',
    name: 'Gen-Z TikTok Launch',
    objective: 'Traffic',
    status: 'paused',
    dailyBudget: 267,
    totalBudget: 8000,
    spend: 7200,
    impressions: 166000,
    clicks: 9462,
    conversions: 142,
    ctr: 5.7,
    cpc: 0.76,
    roas: 5.1,
    estimatedROAS: 5.3,
    adsCount: 5,
    startDate: '2026-02-01',
    lastUpdated: '2026-04-18T14:20:00Z',
  },
];

// ─── Platform Sync History ────────────────────────────────────────────────────
export const mockSyncHistory: PlatformSyncEvent[] = [
  {
    id: 'sync1',
    platform: 'meta',
    status: 'success',
    adsImported: 24,
    campaignsImported: 4,
    startedAt: '2026-05-06T06:00:00Z',
    finishedAt: '2026-05-06T06:02:41Z',
  },
  {
    id: 'sync2',
    platform: 'meta',
    status: 'success',
    adsImported: 21,
    campaignsImported: 4,
    startedAt: '2026-04-29T06:00:00Z',
    finishedAt: '2026-04-29T06:01:58Z',
  },
  {
    id: 'sync3',
    platform: 'meta',
    status: 'error',
    adsImported: 0,
    campaignsImported: 0,
    startedAt: '2026-04-22T07:30:00Z',
    finishedAt: '2026-04-22T07:30:08Z',
    note: 'Rate limit reached — retried automatically after 2 hours',
  },
  {
    id: 'sync4',
    platform: 'meta',
    status: 'success',
    adsImported: 19,
    campaignsImported: 3,
    startedAt: '2026-04-15T06:00:00Z',
    finishedAt: '2026-04-15T06:01:44Z',
  },
];

// ─── Platform Recommendations ─────────────────────────────────────────────────
export const mockPlatformRecommendations: PlatformRecommendation[] = [
  {
    id: 'pr1',
    platform: 'meta',
    campaignId: 'ic3',
    campaignName: 'GlowLab Remarketing',
    type: 'scale',
    title: 'Scale GlowLab Remarketing',
    description: 'Real ROAS 8.2x exceeds the estimated 7.9x projection. Budget utilisation at 61% suggests room to scale daily spend by 30% without efficiency loss.',
    impact: 'high',
    confidence: 87,
  },
  {
    id: 'pr2',
    platform: 'meta',
    campaignId: 'ic2',
    campaignName: 'Spring Conversion Push',
    type: 'budget_shift',
    title: 'Shift Budget from Q1 Awareness',
    description: 'Spring Conversion Push (6.1x ROAS) outperforms Q1 Brand Awareness (5.4x) by 13%. Reallocating 20% of Awareness budget to Conversions may increase overall return.',
    impact: 'medium',
    confidence: 79,
  },
  {
    id: 'pr3',
    platform: 'meta',
    campaignId: 'ic4',
    campaignName: 'Gen-Z TikTok Launch',
    type: 'creative',
    title: 'Refresh Creative — Gen-Z Launch',
    description: 'Campaign is paused with 7.2k of 8k budget spent. ROAS of 5.1x sits 3.8% below projection. Recommend testing 2 new UGC-style creatives before resuming.',
    impact: 'medium',
    confidence: 73,
  },
  {
    id: 'pr4',
    platform: 'google',
    type: 'audience',
    title: 'Connect Google Ads for full picture',
    description: 'Connecting Google Ads would reveal search intent overlap with Meta audiences — typically reduces blended CPA 15–25% through cross-platform budget allocation.',
    impact: 'high',
    confidence: 0,
  },
];

// ─── Global Patterns (cross-ad analysis) ─────────────────────────────────────
export const globalPatterns = [
  { name: 'Pain-Point Hook', avgROAS: 6.8, avgCTR: 4.9, adsUsing: 4, trend: 'up' as const },
  { name: 'Specific Social Proof', avgROAS: 5.9, avgCTR: 4.2, adsUsing: 6, trend: 'up' as const },
  { name: 'Risk Reversal / Guarantee', avgROAS: 6.1, avgCTR: 4.4, adsUsing: 3, trend: 'stable' as const },
  { name: 'Scarcity / Urgency', avgROAS: 4.2, avgCTR: 7.8, adsUsing: 2, trend: 'down' as const },
  { name: 'Authority Credentialing', avgROAS: 7.1, avgCTR: 5.6, adsUsing: 2, trend: 'up' as const },
  { name: 'UGC Style Visuals', avgROAS: 5.4, avgCTR: 5.1, adsUsing: 3, trend: 'up' as const },
  { name: 'Platform-Native Language', avgROAS: 4.8, avgCTR: 4.7, adsUsing: 4, trend: 'stable' as const },
  { name: 'Generic Stock Photos', avgROAS: 2.9, avgCTR: 2.4, adsUsing: 5, trend: 'down' as const },
];

// ─── Pricing Plans ─────────────────────────────────────────────────────────────
// To change prices or features: edit the relevant object in this array.
// The UI renders plans via .map() — no hardcoded cards to update.
export const pricingPlans: PricingPlan[] = [
  {
    id: 'starter',
    name: 'Starter',
    priceMonthly: 19,
    priceLabel: 'US$19/month',
    shortDesc: 'For entrepreneurs and small businesses.',
    features: [
      'AI ad generation',
      'Campaign ideas',
      'Copy for Facebook, Instagram, TikTok & Google',
      'Basic estimated projections',
      'Limited history',
      '1 brand/workspace',
      'No Meta/Google Ads connection',
    ],
    action: 'downgrade',
    actionLabel: 'Downgrade',
  },
  {
    id: 'pro',
    name: 'Pro',
    priceMonthly: 79,
    priceLabel: 'US$79/month',
    shortDesc: 'For businesses that create ads frequently.',
    badge: 'Current Plan',
    badgeVariant: 'emerald',
    features: [
      'More monthly generations',
      'AI A/B variations',
      'Copy, CTA, image & audience analysis',
      'Advanced estimated projections',
      'Campaign history',
      'Export ads ready to publish',
      'Up to 3 brands/workspaces',
    ],
    action: 'current',
    actionLabel: 'Current Plan',
  },
  {
    id: 'performance',
    name: 'Performance',
    priceMonthly: 149,
    priceLabel: 'US$149/month',
    shortDesc: 'For businesses that want to measure real results.',
    badge: 'Most Recommended',
    badgeVariant: 'amber',
    features: [
      'Meta Ads connection',
      'Google Ads connection',
      'Import real campaigns',
      'View real performance metrics',
      'Compare estimated vs real results',
      'Performance dashboard',
      'Smart recommendations',
      'Low performance alerts',
    ],
    action: 'upgrade',
    actionLabel: 'Upgrade',
  },
  {
    id: 'agency',
    name: 'Agency',
    priceMonthly: 299,
    priceLabel: 'US$299/month',
    shortDesc: 'For small agencies or freelancers.',
    features: [
      'Multiple clients & brands',
      'Multiple ad accounts',
      'Client reports',
      'Full history',
      'Team users',
      'Premium templates',
      'Advanced dashboard',
    ],
    action: 'upgrade',
    actionLabel: 'Upgrade',
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    priceMonthly: null,
    priceLabel: 'From US$599/month',
    shortDesc: 'For large agencies or enterprises.',
    features: [
      'Priority support',
      'Guided implementation',
      'White-label reports',
      'Custom automations',
      'Multiple ad accounts',
      'Monthly strategy session',
    ],
    action: 'contact',
    actionLabel: 'Contact Sales',
  },
];
